### ISSUE TITLE
Inline table unexpected key value

### ISSUE THREAD

**Issue by arnau** [Lepzulnag/ion-parser#3]
Hi, when I use inline tables I see an unexpected trailing space.

I would expect that

```toml
foo = { x = 1 }
```

and

```toml
[foo]
x = 1
```

Both result in

```js
{ foo: { x: 1 } }
```

But instead, the inline table results in

```js
{ "foo ": { x: 1 } }
```

**Comment by Lepzulnag** [comment]
Thanks for the bug report mate! I fixed it and the correction is published.

**Comment by arnau** [comment]
Nice one! thanks for fixing this that fast :)
